# Generated by Django 5.2.6 on 2025-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank=True, null=True),
        ),
    ]
