# Generated by Django 5.2.6 on 2025-09-21 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_campaign_status'),
        ('users', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('objective', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')])),
                ('hours_required', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('to_do', 'To-Do'), ('in_progress', 'In-Progress'), ('completed', 'Completed')], default='pending')),
                ('notes', models.TextField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.employee')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='campaigns.campaign')),
            ],
        ),
    ]
