# Generated by Django 5.2.6 on 2025-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
