# Generated by Django 5.2.6 on 2025-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=128),
        ),
    ]
