# Generated by Django 5.2.6 on 2025-09-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_contract_created_at_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractclause',
            name='contract',
        ),
        migrations.AddField(
            model_name='contractclause',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='campaigns.contract'),
        ),
    ]
