# Generated by Django 5.2.6 on 2025-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='name',
            new_name='title',
        ),
    ]
